apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    name: guestbook-service
    app: guestbook
    tier: frontend
spec:
  ports:
  - port: 80

  selector:
    name: guestbook-app-pod
    app: guestbook
    tier: frontend

