apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-deploy
  labels:
    app: guestbook
    name: guestbook-deploy
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: guestbook-deploy
      tier: frontend
  template:
    metadata:
      name: guestbook-app-pod
      labels:
        name: guestbook-app-pod
        app: guestbook
        tier: frontend


    spec:
      containers:
        - name: guestbook
          image: gcr.io/google-samples/gb-frontend:v4
          ports:
              containerPort: 80

