apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: guestbook
    tier: backend

spec:
   ports:
   - port: 6379
     targetPort: 6379
   selector:
     name: redis-pod
     app: guestbook
     tier: backend
