apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  labels:
    app: redis
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-deploy
      app: guestbook
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: guestbook
        tier: backend

    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379