apiVersion: apps/v1
kind: Deployment
metadata:
  name: dba-slave
  labels:
    app: dba-slave
    tier: backend


spec:
  selector:
    matchLabels:
      app: dba-slave
      tier: backend
  replicas: 2

  template:
      metadata:
        name: dba-slave
        labels:
          app: dba-slave
          tier: backend
      spec:
        containers:
          - name: dba-slave
            image: docker pull redis
            ports:
              - containerPort: 80