apiVersion: apps/v1

kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: redis
    tier: backend
spec:
  replicas: 1
  template:

    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: redis

    spec:
      containers:
        - name: redis-backend
          image: redis
          ports :
            - containerPort: 6379


               